version: "3.8"

services:
  mongo:
    image: aashreys/mongo-auth:latest
    container_name: mongodb    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
