version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    container_name: mysql-server
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=1