version: '3.7'
services:
    postgres:
        container_name: postgres2
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=john
          - POSTGRES_PASSWORD=1234
          - POSTGRES_DB=example
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
        networks:
          - dev

networks:
  dev:
    driver: bridge
