version: '3.3'
volumes:
  data:
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server-test
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    # volumes:
    #   - data:/var/opt/mssql/data

