services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8001:8000'
    restart: "no"
